# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 15:45
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='country',
            field=django_countries.fields.CountryField(default='select country', max_length=2),
        ),
    ]
