# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 06:35
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171024_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
