# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171025_0446'),
        ('home', '0003_auto_20171026_0635'),
    ]

    operations = [
    ]
