"""
Django settings for floodSite project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
from machina import get_apps as get_machina_apps
from machina import MACHINA_MAIN_TEMPLATE_DIR
from machina import MACHINA_MAIN_STATIC_DIR

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(PROJECT_ROOT)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z#*k591@z@g_sl_zlwd2u7f1j$libr2ycl6aly@3uv_s#)xd7t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'dashboard',
    #third party
    'crispy_forms',
    'rest_framework',
    #'forum',
    'schedule',
    'myTodo',
    'registration',
    'djangobower',
    'django_countries',

    #machina forum related apps:
    'mptt',
    'haystack',
    'widget_tweaks',
] + get_machina_apps()

BOWER_INSTALLED_APPS = [
    'jquery',
    'jquery-ui',
    'bootstrap',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #machina
    'machina.apps.forum_permission.middleware.ForumPermissionMiddleware',
]

ROOT_URLCONF = 'floodSite.urls'

TEMPLATES = [

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,"templates"),
            MACHINA_MAIN_TEMPLATE_DIR,
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
                #machina
                'machina.core.context_processors.metadata',
            ],
            #'loaders': [
            #    'django.template.loaders.filesystems.Loader',
            #    'django.template.loaders.app_directories.Loader',
            #]
        },
    },
]

WSGI_APPLICATION = 'floodSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


#MACHINA CACHES
CACHES = {
  'default': {
    'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
  },
  'machina_attachments': {
    'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
    'LOCATION': '/tmp',
  }
}

#MACHINA HAYSTACKING
HAYSTACK_CONNECTIONS = {
  'default': {
    'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
    'PATH': os.path.join(os.path.abspath(os.path.dirname(__file__)), 'whoosh_index'),
  },
}

# MACHINA SETTINGS
MACHINA_FORUM_NAME = 'Before the Flood: Forum'
MACHINA_BASE_TEMPLATE_NAME = 'forum_base.html'

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
#this is for development
STATIC_URL = '/static/'

#the server where  it will go to when live
# STATIC_ROOT = "/var/www/example.com/static/"

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR),"static")

STATICFILES_DIRS = (
    os.path.join(BASE_DIR,"static"),
    #machina
    MACHINA_MAIN_STATIC_DIR,
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR),"media")

#login settings
LOGIN_REDIRECT_URL = '/'

#REGISTRATION REDUX
REGISTRATION_FORM = 'home.forms.ProfileForm'
REGISTRATION_OPEN = True
SIMPLE_BACKEND_REDIRECT_URL = '/'
ACCOUNT_ACTIVATION_DAYS = 7
REGISTRATION_EMAIL_HTML = False
REGISTRATION_AUTO_LOGIN = True
SITE_ID = 1



#CRISPY FORM TAGS SETTINGS
CRISPY_TEMPLATE_PACK = 'bootstrap3'

#DJANGO-SCHEDULER SETTINGS
# STATICFILES_FINDERS = ['djangobower.finders.BowerFinder',]
BOWER_COMPONENTS_ROOT = 'bower_components/'

#
# AUTH_USER_MODEL = 'core.User'
#
# CSRF_COOKIE_DOMAIN = None
