# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 07:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 10, 27, 7, 39, 20, 596753, tzinfo=utc))),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
