# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_auto_20171026_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 10, 26, 12, 59, 55, 964791, tzinfo=utc))),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MyProfile')),
            ],
        ),
    ]
