# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 9, 56, 16, 947593, tzinfo=utc)),
        ),
    ]
