# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created',
            new_name='dueDate',
        ),
    ]
