# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 07:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTodo', '0002_auto_20171027_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 27, 7, 41, 29, 393370, tzinfo=utc)),
        ),
    ]
