# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myTodo', '0002_auto_20171022_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='dueDate',
            new_name='date',
        ),
    ]
