# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTodo', '0003_auto_20171027_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 27, 7, 50, 52, 656153, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
