# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 04:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTodo', '0003_auto_20171022_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.TextField(default='No'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 4, 41, 0, 401765, tzinfo=utc)),
        ),
    ]
