# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 04:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTodo', '0004_auto_20171022_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 4, 41, 54, 623753, tzinfo=utc)),
        ),
    ]
