# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myTodo', '0004_auto_20171027_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 28, 3, 58, 49, 542839, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
