# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 07:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTodo', '0006_auto_20171028_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 28, 7, 25, 18, 591657, tzinfo=utc)),
        ),
    ]
