# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-22 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTodo', '0007_auto_20171022_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 5, 42, 7, 156526, tzinfo=utc)),
        ),
    ]
