# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 07:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTodo', '0008_auto_20171028_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 28, 7, 43, 48, 207754, tzinfo=utc)),
        ),
    ]
