# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 12:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myTodo', '0015_auto_20171023_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 23, 12, 3, 18, 249825, tzinfo=utc)),
        ),
    ]
