# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 22:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTodo', '0016_auto_20171023_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 23, 22, 42, 56, 438655, tzinfo=utc)),
        ),
    ]
