# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-24 05:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myTodo', '0017_auto_20171023_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 24, 5, 14, 11, 842619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.MyProfile'),
        ),
    ]
